\input texinfo
@settitle ACT I

@ifnottex
@node Top
@top A info sample
@end ifnottex

@menu
* First Chapter::    The cat
* Second Chapter::    The hat
@end menu

@node First Chapter
@chapter First Chapter

The cat sat in the hat

@node Second Chapter
@chapter Second Chapter

The hat purred smuggly, much to the annoyance of the cat.

@bye
